// UK structural steel fabrication mock data for Titan SteelQuote
// TODO: Replace all mock data with API/database calls when backend is implemented

import type {
  Customer,
  Enquiry,
  SteelMaterialLine,
  LabourOperation,
  EstimateSummary,
  MaterialRate,
  LabourRate,
  User,
  ActivityEntry,
  Document,
  OrgSettings,
} from './types'

// ─── Users ────────────────────────────────────────────────────────────────────

export const mockUsers: User[] = [
  { id: 'u1', name: 'James Hartley', initials: 'JH', role: 'Senior Estimator', email: 'j.hartley@titansteel.co.uk', active: true },
  { id: 'u2', name: 'Rachel Okafor', initials: 'RO', role: 'Estimator', email: 'r.okafor@titansteel.co.uk', active: true },
  { id: 'u3', name: 'David Birch', initials: 'DB', role: 'Estimating Manager', email: 'd.birch@titansteel.co.uk', active: true },
  { id: 'u4', name: 'Sophie Nkemdirim', initials: 'SN', role: 'Estimator', email: 's.nkemdirim@titansteel.co.uk', active: true },
  { id: 'u5', name: 'Tom Ashworth', initials: 'TA', role: 'Director', email: 't.ashworth@titansteel.co.uk', active: true },
]

// ─── Customers ────────────────────────────────────────────────────────────────

export const mockCustomers: Customer[] = [
  {
    id: 'c1',
    name: 'Vanguard Construction Ltd',
    type: 'Main Contractor',
    address: '12 Waterloo Road',
    city: 'Leeds',
    postcode: 'LS1 2AB',
    country: 'UK',
    primaryContact: 'Paul Gregson',
    email: 'p.gregson@vanguardconstruction.co.uk',
    phone: '0113 280 4500',
    website: 'www.vanguardconstruction.co.uk',
    activeEnquiries: 3,
    wonJobs: 14,
    totalValue: 4820000,
    createdAt: '2021-03-10',
    updatedAt: '2025-06-12',
  },
  {
    id: 'c2',
    name: 'Meridian Property Developments',
    type: 'Developer',
    address: '45 King Street',
    city: 'Manchester',
    postcode: 'M2 6AZ',
    country: 'UK',
    primaryContact: 'Claire Sutton',
    email: 'c.sutton@meridianpd.co.uk',
    phone: '0161 834 2100',
    website: 'www.meridianpd.co.uk',
    activeEnquiries: 2,
    wonJobs: 7,
    totalValue: 2310000,
    createdAt: '2022-01-18',
    updatedAt: '2025-07-01',
  },
  {
    id: 'c3',
    name: 'Hallsworth Civil Engineering',
    type: 'Main Contractor',
    address: '8 Forge Lane',
    city: 'Sheffield',
    postcode: 'S9 3QS',
    country: 'UK',
    primaryContact: 'Mark Hallsworth',
    email: 'm.hallsworth@hallsworthcivil.co.uk',
    phone: '0114 256 8800',
    activeEnquiries: 1,
    wonJobs: 22,
    totalValue: 7650000,
    createdAt: '2019-07-04',
    updatedAt: '2025-05-30',
  },
  {
    id: 'c4',
    name: 'Northern Health Estates',
    type: 'Public Sector',
    address: 'Civic Centre, Deansgate',
    city: 'Bolton',
    postcode: 'BL1 1JW',
    country: 'UK',
    primaryContact: 'Karen Price',
    email: 'k.price@northernhealthestates.nhs.uk',
    phone: '01204 336 000',
    activeEnquiries: 1,
    wonJobs: 5,
    totalValue: 1940000,
    createdAt: '2020-11-22',
    updatedAt: '2025-07-10',
  },
  {
    id: 'c5',
    name: 'Blackthorn Industrial Developments',
    type: 'Developer',
    address: '102 Commerce Street',
    city: 'Doncaster',
    postcode: 'DN1 3HF',
    country: 'UK',
    primaryContact: 'Gary Thornton',
    email: 'gary.thornton@blackthorn-ind.co.uk',
    phone: '01302 445 900',
    activeEnquiries: 2,
    wonJobs: 11,
    totalValue: 3280000,
    createdAt: '2021-09-14',
    updatedAt: '2025-06-28',
  },
  {
    id: 'c6',
    name: 'Pennine Infrastructure Partners',
    type: 'Main Contractor',
    address: '3 Pennine Way',
    city: 'Halifax',
    postcode: 'HX1 3LW',
    country: 'UK',
    primaryContact: 'Stuart Featherstone',
    email: 's.featherstone@pennine-ip.co.uk',
    phone: '01422 318 700',
    activeEnquiries: 1,
    wonJobs: 8,
    totalValue: 2140000,
    createdAt: '2022-06-01',
    updatedAt: '2025-07-08',
  },
]

// ─── Enquiries ────────────────────────────────────────────────────────────────

export const mockEnquiries: Enquiry[] = [
  {
    id: 'enq-001',
    enquiryNumber: 'ENQ-2025-0142',
    customerId: 'c1',
    customerName: 'Vanguard Construction Ltd',
    project: 'Kirkstall Road Distribution Hub',
    projectAddress: 'Plot 7, Kirkstall Road Industrial Estate, Leeds, LS5 3BT',
    contactName: 'Paul Gregson',
    receivedDate: '2025-06-30',
    tenderDeadline: '2025-07-28',
    estimatorId: 'u1',
    estimatorName: 'James Hartley',
    status: 'In Progress',
    source: 'Main Contractor',
    estimatedValue: 485000,
    probability: 65,
    description: 'Structural steel frame for new 8,500m² logistics and distribution building including mezzanine floor, canopy and loading dock steelwork.',
    notes: 'Client has indicated programme is tight. Phased delivery may be required.',
    inclusions: ['Supply and erect structural steelwork', 'Hot-dip galvanise all external members', 'Provision of temporary works design', 'Cert A structural steel'],
    exclusions: ['Cladding rails and purlins', 'Concrete groundworks', 'Architectural metalwork'],
    assumptions: ['Foundations provided by others', 'Crane access available throughout', 'No abnormal ground conditions'],
    paymentTerms: '30 days net from invoice date',
    quoteValidity: '60 days from issue date',
    lastUpdated: '2025-07-10',
    createdAt: '2025-06-30',
    documents: [],
    revisions: [],
  },
  {
    id: 'enq-002',
    enquiryNumber: 'ENQ-2025-0143',
    customerId: 'c2',
    customerName: 'Meridian Property Developments',
    project: 'Ancoats Apartments Phase 2',
    projectAddress: 'Blossom Street, Ancoats, Manchester, M4 6AJ',
    contactName: 'Claire Sutton',
    receivedDate: '2025-07-01',
    tenderDeadline: '2025-07-25',
    estimatorId: 'u2',
    estimatorName: 'Rachel Okafor',
    status: 'New',
    source: 'Client Direct',
    estimatedValue: 312000,
    probability: 40,
    description: 'Structural steel for 7-storey residential development. Mixed use ground floor with residential above. Long-span beams to ground floor retail.',
    notes: '',
    lastUpdated: '2025-07-01',
    createdAt: '2025-07-01',
    documents: [],
    revisions: [],
  },
  {
    id: 'enq-003',
    enquiryNumber: 'ENQ-2025-0138',
    customerId: 'c3',
    customerName: 'Hallsworth Civil Engineering',
    project: 'Sheffield Tram Infrastructure Shed',
    projectAddress: 'Nunnery Square, Sheffield, S2 5PF',
    contactName: 'Mark Hallsworth',
    receivedDate: '2025-06-15',
    tenderDeadline: '2025-07-22',
    estimatorId: 'u1',
    estimatorName: 'James Hartley',
    status: 'Priced',
    source: 'Main Contractor',
    estimatedValue: 920000,
    probability: 75,
    description: 'Large-span maintenance shed for tram rolling stock. Clear span portal frames, gantry crane beams and inspection pit steelwork.',
    lastUpdated: '2025-07-08',
    createdAt: '2025-06-15',
    documents: [],
    revisions: [{ id: 'rev-001', enquiryId: 'enq-003', quoteNumber: 'QTE-2025-0089', revision: 1, sellingPrice: 924500, status: 'Issued', issuedAt: '2025-07-08', validUntil: '2025-09-06', createdAt: '2025-07-08' }],
  },
  {
    id: 'enq-004',
    enquiryNumber: 'ENQ-2025-0134',
    customerId: 'c4',
    customerName: 'Northern Health Estates',
    project: 'Bolton Royal Infirmary – Plant Room Extension',
    projectAddress: 'Minerva Road, Bolton, BL4 0JR',
    contactName: 'Karen Price',
    receivedDate: '2025-06-10',
    tenderDeadline: '2025-07-18',
    estimatorId: 'u3',
    estimatorName: 'David Birch',
    status: 'Submitted',
    source: 'Framework Agreement',
    estimatedValue: 148000,
    probability: 80,
    description: 'Structural steelwork for single-storey plant room extension to existing hospital building. Working within existing structure.',
    lastUpdated: '2025-07-12',
    createdAt: '2025-06-10',
    documents: [],
    revisions: [{ id: 'rev-002', enquiryId: 'enq-004', quoteNumber: 'QTE-2025-0092', revision: 1, sellingPrice: 149800, status: 'Issued', issuedAt: '2025-07-12', validUntil: '2025-09-10', createdAt: '2025-07-12' }],
  },
  {
    id: 'enq-005',
    enquiryNumber: 'ENQ-2025-0131',
    customerId: 'c5',
    customerName: 'Blackthorn Industrial Developments',
    project: 'Doncaster FMCG Warehouse',
    projectAddress: 'Redhouse Industrial Estate, Doncaster, DN3 2FD',
    contactName: 'Gary Thornton',
    receivedDate: '2025-05-28',
    tenderDeadline: '2025-07-05',
    estimatorId: 'u2',
    estimatorName: 'Rachel Okafor',
    status: 'Won',
    source: 'Client Direct',
    estimatedValue: 1280000,
    probability: 100,
    description: 'Twin-portal frame industrial warehouse 12,000m² including dock levellers, mezzanine floors and sprinkler support steelwork.',
    lastUpdated: '2025-07-05',
    createdAt: '2025-05-28',
    documents: [],
    revisions: [],
  },
  {
    id: 'enq-006',
    enquiryNumber: 'ENQ-2025-0128',
    customerId: 'c1',
    customerName: 'Vanguard Construction Ltd',
    project: 'Harrogate Retail Park Phase 3',
    projectAddress: 'Stonefall Avenue, Harrogate, HG2 7BZ',
    contactName: 'Paul Gregson',
    receivedDate: '2025-05-20',
    tenderDeadline: '2025-06-30',
    estimatorId: 'u4',
    estimatorName: 'Sophie Nkemdirim',
    status: 'Lost',
    source: 'Main Contractor',
    estimatedValue: 560000,
    probability: 0,
    description: 'Steel frame for new retail units. Mix of portal frames and flat roof steel.',
    lastUpdated: '2025-07-02',
    createdAt: '2025-05-20',
    documents: [],
    revisions: [],
  },
  {
    id: 'enq-007',
    enquiryNumber: 'ENQ-2025-0144',
    customerId: 'c6',
    customerName: 'Pennine Infrastructure Partners',
    project: 'Calderdale Flood Defence Bridge',
    projectAddress: 'Calder Road, Hebden Bridge, HX7 6AS',
    contactName: 'Stuart Featherstone',
    receivedDate: '2025-07-03',
    tenderDeadline: '2025-08-08',
    estimatorId: 'u3',
    estimatorName: 'David Birch',
    status: 'Awaiting Info',
    source: 'Structural Engineer',
    estimatedValue: 390000,
    probability: 55,
    description: 'Structural steelwork for new pedestrian and cycle bridge as part of flood alleviation scheme. Weather-resistant steel (Corten) specification.',
    notes: 'Awaiting updated structural drawings and ground investigation report.',
    lastUpdated: '2025-07-09',
    createdAt: '2025-07-03',
    documents: [],
    revisions: [],
  },
  {
    id: 'enq-008',
    enquiryNumber: 'ENQ-2025-0146',
    customerId: 'c5',
    customerName: 'Blackthorn Industrial Developments',
    project: 'Rotherham Multi-Storey Car Park',
    projectAddress: 'Corporation Street, Rotherham, S60 1RF',
    contactName: 'Gary Thornton',
    receivedDate: '2025-07-07',
    tenderDeadline: '2025-08-01',
    estimatorId: 'u1',
    estimatorName: 'James Hartley',
    status: 'In Progress',
    source: 'Client Direct',
    estimatedValue: 2100000,
    probability: 50,
    description: '7-storey post-tensioned concrete multi-storey car park with structural steel cores, stair and lift shaft steelwork.',
    lastUpdated: '2025-07-11',
    createdAt: '2025-07-07',
    documents: [],
    revisions: [],
  },
]

// ─── Material Lines ────────────────────────────────────────────────────────────

export const mockMaterialLines: SteelMaterialLine[] = [
  { id: 'ml-001', enquiryId: 'enq-001', mark: 'A1', section: 'UC 254x254x89', grade: 'S355', lengthMm: 8400, quantity: 12, unitWeightKgm: 89.0, totalWeightKg: 8971.2, pricePerTonne: 920, wastePercent: 2.5, totalCost: 8455.03, validationStatus: 'Valid' },
  { id: 'ml-002', enquiryId: 'enq-001', mark: 'A2', section: 'UC 203x203x60', grade: 'S355', lengthMm: 6000, quantity: 24, unitWeightKgm: 60.0, totalWeightKg: 8640.0, pricePerTonne: 920, wastePercent: 2.5, totalCost: 8136.0, validationStatus: 'Valid' },
  { id: 'ml-003', enquiryId: 'enq-001', mark: 'B1', section: 'UB 457x191x89', grade: 'S355', lengthMm: 14600, quantity: 8, unitWeightKgm: 89.3, totalWeightKg: 10430.56, pricePerTonne: 895, wastePercent: 2.5, totalCost: 9585.10, validationStatus: 'Valid' },
  { id: 'ml-004', enquiryId: 'enq-001', mark: 'B2', section: 'UB 356x171x57', grade: 'S355', lengthMm: 9000, quantity: 16, unitWeightKgm: 57.0, totalWeightKg: 8208.0, pricePerTonne: 895, wastePercent: 2.5, totalCost: 7541.16, validationStatus: 'Valid' },
  { id: 'ml-005', enquiryId: 'enq-001', mark: 'R1', section: 'RHS 200x100x8', grade: 'S355J2H', lengthMm: 6000, quantity: 30, unitWeightKgm: 37.1, totalWeightKg: 6678.0, pricePerTonne: 1100, wastePercent: 3.0, totalCost: 7566.18, validationStatus: 'Valid' },
  { id: 'ml-006', enquiryId: 'enq-001', mark: 'P1', section: 'PFC 260x75', grade: 'S275', lengthMm: 3600, quantity: 48, unitWeightKgm: 28.0, totalWeightKg: 4838.4, pricePerTonne: 870, wastePercent: 2.5, totalCost: 4318.67, validationStatus: 'Warning', validationMessage: 'Section weight unconfirmed — verify against BS4 Table 3' },
  { id: 'ml-007', enquiryId: 'enq-001', mark: 'PL1', section: 'Flat Plate 20mm', grade: 'S355', lengthMm: 2400, quantity: 60, unitWeightKgm: 0, totalWeightKg: 2260.8, pricePerTonne: 1050, wastePercent: 5.0, totalCost: 2445.00, validationStatus: 'Valid' },
  { id: 'ml-008', enquiryId: 'enq-001', mark: 'PL2', section: 'Flat Plate 10mm', grade: 'S275', lengthMm: 1200, quantity: 120, unitWeightKgm: 0, totalWeightKg: 1131.0, pricePerTonne: 980, wastePercent: 5.0, totalCost: 1140.0, validationStatus: 'Error', validationMessage: 'Quantity exceeds schedule total — check drawing revision' },
]

// ─── Labour Operations ─────────────────────────────────────────────────────────

export const mockLabourOperations: LabourOperation[] = [
  { id: 'lo-001', enquiryId: 'enq-001', operation: 'Marking Out', description: 'Layout, centre punch and mark all connections and bolt holes', quantity: 1, setupHours: 2.0, unitHours: 18.5, totalHours: 20.5, hourlyRate: 42.0, totalLabourCost: 861.0 },
  { id: 'lo-002', enquiryId: 'enq-001', operation: 'Drilling', description: 'Drill all connection holes to approved drawings', quantity: 1, setupHours: 1.5, unitHours: 22.0, totalHours: 23.5, hourlyRate: 42.0, totalLabourCost: 987.0 },
  { id: 'lo-003', enquiryId: 'enq-001', operation: 'Cutting', description: 'Saw cut and profile cut all members to length', quantity: 1, setupHours: 2.0, unitHours: 16.0, totalHours: 18.0, hourlyRate: 38.0, totalLabourCost: 684.0 },
  { id: 'lo-004', enquiryId: 'enq-001', operation: 'Welding – Fabrication', description: 'MIG/MAG welding of all connections and end plates', quantity: 1, setupHours: 4.0, unitHours: 68.0, totalHours: 72.0, hourlyRate: 48.0, totalLabourCost: 3456.0 },
  { id: 'lo-005', enquiryId: 'enq-001', operation: 'Welding – NDT Prep', description: 'Grinding and preparation of welds for NDT inspection', quantity: 1, setupHours: 1.0, unitHours: 8.0, totalHours: 9.0, hourlyRate: 44.0, totalLabourCost: 396.0 },
  { id: 'lo-006', enquiryId: 'enq-001', operation: 'Shotblasting', description: 'Abrasive blast clean to Sa 2.5 per BS EN ISO 8501', quantity: 1, setupHours: 2.0, unitHours: 14.0, totalHours: 16.0, hourlyRate: 40.0, totalLabourCost: 640.0 },
  { id: 'lo-007', enquiryId: 'enq-001', operation: 'Primer Painting', description: 'Apply two coats zinc phosphate primer (DFT 75 microns)', quantity: 1, setupHours: 1.5, unitHours: 12.0, totalHours: 13.5, hourlyRate: 38.0, totalLabourCost: 513.0 },
  { id: 'lo-008', enquiryId: 'enq-001', operation: 'Erection', description: 'Site erection of structural steelwork including all connections', quantity: 1, setupHours: 8.0, unitHours: 96.0, totalHours: 104.0, hourlyRate: 52.0, totalLabourCost: 5408.0 },
]

// ─── Estimate ─────────────────────────────────────────────────────────────────

export const mockEstimate: EstimateSummary = {
  id: 'est-001',
  enquiryId: 'enq-001',
  revision: 1,
  materials: 49187.14,
  labour: 12945.0,
  consumables: 1450.0,
  coating: 3200.0,
  subcontracting: 4800.0,
  transport: 2850.0,
  plant: 3600.0,
  overheadPercent: 18.0,
  overheadValue: 14042.05,
  contingencyPercent: 3.0,
  contingencyValue: 2774.95,
  totalEstimatedCost: 94849.14,
  targetMarginPercent: 14.5,
  sellingPrice: 110934.37,
  profit: 16085.23,
  effectiveMarginPercent: 14.5,
  status: 'Draft',
  createdAt: '2025-07-10',
}

// ─── Activity ─────────────────────────────────────────────────────────────────

export const mockActivityLog: ActivityEntry[] = [
  { id: 'act-001', enquiryId: 'enq-001', userId: 'u1', userName: 'James Hartley', action: 'Enquiry created', timestamp: '2025-06-30T09:12:00Z', type: 'edit' },
  { id: 'act-002', enquiryId: 'enq-001', userId: 'u1', userName: 'James Hartley', action: 'Documents uploaded', detail: 'Structural drawings issue A (4 files)', timestamp: '2025-07-01T11:34:00Z', type: 'document' },
  { id: 'act-003', enquiryId: 'enq-001', userId: 'u1', userName: 'James Hartley', action: 'Steel schedule imported', detail: '8 line items, 49.7t total', timestamp: '2025-07-02T14:08:00Z', type: 'estimate' },
  { id: 'act-004', enquiryId: 'enq-001', userId: 'u3', userName: 'David Birch', action: 'Comment added', detail: 'Check hot-dip galvanising requirement — client spec section 8.3 may require full immersion bath only.', timestamp: '2025-07-03T10:20:00Z', type: 'comment' },
  { id: 'act-005', enquiryId: 'enq-001', userId: 'u1', userName: 'James Hartley', action: 'Status changed', detail: 'New → In Progress', timestamp: '2025-07-04T08:45:00Z', type: 'status_change' },
  { id: 'act-006', enquiryId: 'enq-001', userId: 'u1', userName: 'James Hartley', action: 'Estimate draft saved', detail: 'Rev 1 — selling price £110,934', timestamp: '2025-07-10T16:30:00Z', type: 'estimate' },
]

// ─── Documents ────────────────────────────────────────────────────────────────

export const mockDocuments: Document[] = [
  { id: 'doc-001', enquiryId: 'enq-001', name: 'GA Drawings Issue A – Ground Floor.pdf', type: 'Drawing', size: '4.2 MB', uploadedBy: 'James Hartley', uploadedAt: '2025-07-01T11:34:00Z' },
  { id: 'doc-002', enquiryId: 'enq-001', name: 'GA Drawings Issue A – First Floor.pdf', type: 'Drawing', size: '3.8 MB', uploadedBy: 'James Hartley', uploadedAt: '2025-07-01T11:34:00Z' },
  { id: 'doc-003', enquiryId: 'enq-001', name: 'Structural Specification Rev 0.pdf', type: 'Specification', size: '1.1 MB', uploadedBy: 'James Hartley', uploadedAt: '2025-07-01T11:35:00Z' },
  { id: 'doc-004', enquiryId: 'enq-001', name: 'Steel Schedule v1.csv', type: 'BOM', size: '28 KB', uploadedBy: 'James Hartley', uploadedAt: '2025-07-02T14:08:00Z' },
]

// ─── Material Rates ────────────────────────────────────────────────────────────

export const mockMaterialRates: MaterialRate[] = [
  { id: 'mr-001', section: 'Universal Column (UC)', grade: 'S355', supplier: 'Tata Steel UK', pricePerTonne: 920, wasteAllowancePercent: 2.5, effectiveDate: '2025-01-01', status: 'Current', notes: 'Per long products price list Jan 2025' },
  { id: 'mr-002', section: 'Universal Beam (UB)', grade: 'S355', supplier: 'Tata Steel UK', pricePerTonne: 895, wasteAllowancePercent: 2.5, effectiveDate: '2025-01-01', status: 'Current' },
  { id: 'mr-003', section: 'Universal Beam (UB)', grade: 'S275', supplier: 'Tata Steel UK', pricePerTonne: 875, wasteAllowancePercent: 2.5, effectiveDate: '2025-01-01', status: 'Current' },
  { id: 'mr-004', section: 'Hollow Section (RHS/SHS)', grade: 'S355J2H', supplier: 'Barrett Steel', pricePerTonne: 1100, wasteAllowancePercent: 3.0, effectiveDate: '2025-03-01', status: 'Current', notes: 'HF and CF sections' },
  { id: 'mr-005', section: 'Parallel Flange Channel (PFC)', grade: 'S275', supplier: 'Tata Steel UK', pricePerTonne: 870, wasteAllowancePercent: 2.5, effectiveDate: '2025-01-01', status: 'Current' },
  { id: 'mr-006', section: 'Plate (Flat)', grade: 'S355', supplier: 'Metals4U', pricePerTonne: 1050, wasteAllowancePercent: 5.0, effectiveDate: '2025-04-01', status: 'Current' },
  { id: 'mr-007', section: 'Plate (Flat)', grade: 'S275', supplier: 'Metals4U', pricePerTonne: 980, wasteAllowancePercent: 5.0, effectiveDate: '2025-04-01', status: 'Current' },
  { id: 'mr-008', section: 'Weathering Steel (Corten)', grade: 'S355J0WP', supplier: 'Corus Service Centre', pricePerTonne: 1380, wasteAllowancePercent: 3.0, effectiveDate: '2025-05-01', status: 'Current', notes: 'Architectural and structural grade' },
  { id: 'mr-009', section: 'Angle (EA/UA)', grade: 'S275', supplier: 'Tata Steel UK', pricePerTonne: 840, wasteAllowancePercent: 3.0, effectiveDate: '2024-10-01', expiryDate: '2024-12-31', status: 'Expired' },
  { id: 'mr-010', section: 'Hollow Section (CHS)', grade: 'S355J2H', supplier: 'Barrett Steel', pricePerTonne: 1150, wasteAllowancePercent: 3.0, effectiveDate: '2025-03-01', status: 'Current' },
]

// ─── Labour Rates ─────────────────────────────────────────────────────────────

export const mockLabourRates: LabourRate[] = [
  { id: 'lr-001', operation: 'Marking Out', description: 'Layout, centre punch, mark connection positions', hourlyRate: 42.0, setupTimeHours: 2.0, unitTimeHours: 0.25, effectiveDate: '2025-04-01', status: 'Current' },
  { id: 'lr-002', operation: 'Drilling', description: 'Drill connection holes per approved drawings', hourlyRate: 42.0, setupTimeHours: 1.5, unitTimeHours: 0.08, effectiveDate: '2025-04-01', status: 'Current' },
  { id: 'lr-003', operation: 'Cutting – Saw', description: 'Bandsaw cut to length', hourlyRate: 38.0, setupTimeHours: 1.0, unitTimeHours: 0.05, effectiveDate: '2025-04-01', status: 'Current' },
  { id: 'lr-004', operation: 'Cutting – Profile', description: 'CNC plasma/oxy-fuel profile cutting', hourlyRate: 44.0, setupTimeHours: 2.0, unitTimeHours: 0.12, effectiveDate: '2025-04-01', status: 'Current' },
  { id: 'lr-005', operation: 'Welding – MIG/MAG', description: 'MIG/MAG fabrication welding', hourlyRate: 48.0, setupTimeHours: 3.0, unitTimeHours: 0.35, effectiveDate: '2025-04-01', status: 'Current' },
  { id: 'lr-006', operation: 'Welding – SAW', description: 'Submerged arc welding (heavy plate)', hourlyRate: 52.0, setupTimeHours: 4.0, unitTimeHours: 0.20, effectiveDate: '2025-04-01', status: 'Current' },
  { id: 'lr-007', operation: 'Shotblasting', description: 'Abrasive blast clean Sa 2.5 (BS EN ISO 8501)', hourlyRate: 40.0, setupTimeHours: 2.0, unitTimeHours: 0.04, effectiveDate: '2025-04-01', status: 'Current', notes: 'Rate includes media and PPE consumables' },
  { id: 'lr-008', operation: 'Primer Painting', description: 'Zinc phosphate primer application', hourlyRate: 38.0, setupTimeHours: 1.5, unitTimeHours: 0.03, effectiveDate: '2025-04-01', status: 'Current' },
  { id: 'lr-009', operation: 'Erection', description: 'Site erection of structural steelwork', hourlyRate: 52.0, setupTimeHours: 8.0, unitTimeHours: 0.60, effectiveDate: '2025-04-01', status: 'Current', notes: 'Includes two-man team allowance' },
  { id: 'lr-010', operation: 'NDT – UT', description: 'Ultrasonic testing of welds', hourlyRate: 65.0, setupTimeHours: 1.0, unitTimeHours: 0.15, effectiveDate: '2025-04-01', status: 'Current' },
  { id: 'lr-011', operation: 'Marking Out', description: 'Layout and marking (superseded rate)', hourlyRate: 38.0, setupTimeHours: 2.0, unitTimeHours: 0.25, effectiveDate: '2024-04-01', expiryDate: '2025-03-31', status: 'Expired' },
]

// ─── Org Settings ─────────────────────────────────────────────────────────────

export const mockOrgSettings: OrgSettings = {
  companyName: 'Titan Structural Steelwork Ltd',
  tradingName: 'Titan Steel',
  address: 'Unit 4, Foundry Business Park, Steel Road',
  city: 'Rotherham',
  postcode: 'S60 5QT',
  phone: '01709 823 400',
  email: 'enquiries@titansteel.co.uk',
  website: 'www.titansteel.co.uk',
  vatNumber: 'GB 312 8841 22',
  companyNumber: '07418239',
  quotePrefix: 'QTE',
  quoteStartNumber: 93,
  defaultOverheadPercent: 18.0,
  defaultMarginPercent: 14.5,
  defaultContingencyPercent: 3.0,
  defaultPaymentTerms: '30 days net from invoice date',
  defaultQuoteValidity: '60 days from issue date',
  vatRate: 20.0,
  defaultInclusions: [
    'Supply and fabrication of structural steelwork',
    'CE marking to execution class EXC2 per BS EN 1090-2',
    'Primer coat (75 microns DFT zinc phosphate)',
    'Hot-dip galvanising where specified',
    'Structural design check calculations',
    'Temporary works design allowance',
  ],
  defaultExclusions: [
    'Cladding rails, purlins and sheeting',
    'Concrete groundworks and foundations',
    'Architectural and decorative metalwork',
    'Mechanical, electrical or plumbing works',
    'Building control and planning fees',
  ],
  defaultAssumptions: [
    'Structural loads and connections are as indicated on drawings issued for tender',
    'Foundations and holding down bolts provided by others to our setting-out drawing',
    'Crane access available throughout erection period',
    'No abnormal ground conditions or restricted access',
    'Programme and phasing as discussed',
  ],
}

// ─── Dashboard Stats ──────────────────────────────────────────────────────────

export const dashboardStats = {
  totalLiveEnquiryValue: 4455000,
  quotesAwaitingApproval: 3,
  quotesDueWithin7Days: 4,
  winRate: 62,
  averageQuotedMargin: 13.8,
  monthlyEnquiryCounts: [
    { month: 'Feb', count: 5, value: 1200000 },
    { month: 'Mar', count: 8, value: 2100000 },
    { month: 'Apr', count: 6, value: 1800000 },
    { month: 'May', count: 9, value: 3400000 },
    { month: 'Jun', count: 11, value: 3900000 },
    { month: 'Jul', count: 7, value: 4455000 },
  ],
  statusBreakdown: [
    { status: 'New', count: 2, value: 702000 },
    { status: 'In Progress', count: 3, value: 3385000 },
    { status: 'Awaiting Info', count: 1, value: 390000 },
    { status: 'Priced', count: 2, value: 1460000 },
    { status: 'Submitted', count: 2, value: 298000 },
    { status: 'Won', count: 4, value: 2890000 },
    { status: 'Lost', count: 3, value: 1240000 },
    { status: 'No Bid', count: 1, value: 85000 },
  ],
}
